# Catppuccin Mocha Farben (du kannst diese bei Bedarf anpassen)
palette = "catppuccin_mocha"

format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$golang\
$perl\
$nodejs\
$vagrant\
$cmd_duration\
$line_break\
$username\
$character"""

[directory]
style = "bold blue blink underline"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold mauve"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = "bold mauve"
format = '([\[$all_status$ahead_behind\]]($style)) '

[fill]
symbol = " "

[python]
symbol = "󰌠 "
format = '[${symbol}${version} (\($virtualenv\) )]($style)'

[lua]
symbol = "󰢱 "
format = '[$symbol($version )]($style)'

[golang]
symbol = " "
format = '[$symbol($version )]($style)'	

[perl]
symbol = " "
format = '[$symbol($version )]($style)'
detect_extensions = ['pl', 'ps']

[nodejs]
format = '[$symbol($version )]($style)'

[vagrant]
format = '[$symbol($version )]($style)'

[cmd_duration]
style = "dimmed white"
format = 'took [$duration]($style) '

[username]
show_always = true
style_root = "bold red"
style_user = "green"
format = '[$user]($style) '

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
vimcmd_symbol = "[❮](bold peach)"
error_symbol = "[✗](bold red)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext0  = "#a6adc8"
overlay0  = "#6c7086"
surface2  = "#585b70"
base      = "#1e1e2e"

[custom.cursor_blink]
when = "true"
command = "echo -ne '\u001b[1 q'"
shell = ["bash"]
format = ""
